local = "RTL"  # or "LTR"

strings = {
    "ar": {
        "today": "اليوم",
        "hello": "مرحبا",
        "tomorrow": "غدا",
        "day_after_tomorrow": "ب غدا",
        "noNotifications": "لا توجد أي إشعارات جديدة",
        "notificationCenter": "مركز الإشعارات",
        # Themes
        "black_hole_theme": "ثقب",
        "deer_theme": "غزال",
        "color_theme": "جمالي",
        "siberian_theme": "تدرج",
        "material_you_theme": "مادي",
        "win20_theme": "ويندوز",
        "game_theme": "لعبة",
        "dark_theme": "مظلم",
        "unicat_theme": "قط",
        "new_cat_theme": "قط 2",
        "golden_theme": "ذهبي",
        "harmony_theme": "تناغم",
        "circles_theme": "دوائر",
        "white_flower": "ابيض",
        # Circles Widget
        "linux_title": "لينكس",
        "system_title": "النظام",
        "name_title": "الاسم",
        "host_title": "الهوست",
        "runtime_title": "وقت التشغيل",
        "package_manager_title": "مدير الحزم",
        "packages_title": "الحزم",
        # Prayers
        "prayer_times": "اوقات الصلوات",
        "fajr_prayer": "صلاة الفجر",
        "dhuhr_prayer": "صلاة الظهر",
        "asr_prayer": "صلاة العصر",
        "maghrib_prayer": "صلاة المغرب",
        "isha_prayer": "صلاة العشاء",
        "prayer_time_now": "حان الآن وقت صلاة",
        "fajr": "الفجر",
        "isha": "العشاء",
        "maghrib": "المغرب",
        "asr": "العصر",
        "dhuhr": "الظهر",
        # Weather
        "feels_like": "شعور وكانة",
        "humidity": "الرطوبة",
        "pressure": "الضغط",
        "max_temp": "العليا",
        "min_temp": "الصغرى",
        "wind": "الرياح",
        "clouds": "السحب",
        "min_and_max": "الصغرى والعلياء",
        "cold_weather": "طقس بارد !",
        "hot_weather": "طقس حار !",
        "rainy_weather_title": "جو ممطر",
        "rainy_weather_text": "من المتوقع هطول الامطار اليوم بنسبة",
        "min_temperature": "درجة الحرارة الصغرى اليوم",
        "max_temperature": "درجة الحرارة الكبرى اليوم",
        "weather_not_available": "خدمة الطقس غير متاحة",
        "sunset": "الغروب",
        "sunrise": "الشروق",
        # Fuzzy Widget
        "fuzzy_clock_thursday": "أرحب يالخميس",
        "fuzzy_clock_programming_time": "وقت البرمجة, حان وقت الابداع",
        "fuzzy_clock_morning": "صباح الخير! بداية جديدة ليوم مليء بالفرص",
        "fuzzy_clock_coffee": "بكوب من القهوة، دع الإنجازات تبدأ",
        "fuzzy_clock_lunch": "حان وقت الغداء، استرح واستعد للجولة الثانية",
        "fuzzy_clock_creative": "حان وقت الإبداع، شغف وعمل خفيف ينتظرك",
        "fuzzy_clock_tea": "استمتع بكوب شاي واسترخِ مع كتاب خفيف",
        "fuzzy_clock_dinner": "العشاء جاهز، استمتع بوقتك مع أحبائك",
        "fuzzy_clock_night": "ليلة سعيدة! استرخِ واستعد لغد جديد",
        "fuzzy_clock_play": "استمتع باللعب والمرح، إنها العطلة!",
        "fuzzy_clock_pray": "وقت مثالي للأذكار وقراءة القرآن.",
        "fuzzy_clock_bath": "استحم واستعد لصلاة الجمعة المباركة.",
        "fuzzy_clock_friday_prayer": "حان وقت صلاة الجمعة.",
        "fuzzy_clock_family": "استمتع بالغداء مع العائلة واسترخِ.",
        "fuzzy_clock_friends": "اخرج مع الأصدقاء واستمتع بيومك.",
        "fuzzy_clock_relax": "ليلة سعيدة! استرخِ واستعد ليوم جديد.",
        "fuzzy_day_saturday": "مرحبًا بك في يوم جديد،",
        "fuzzy_day_sunday": "الأحد هو فرصة جديدة",
        "fuzzy_day_monday": "نصف الأسبوع قد حان",
        "fuzzy_day_tuesday": "يوم مليء بالأعمال",
        "fuzzy_day_wednesday": "اليوم هو الأربعاء،",
        "fuzzy_day_friday": "يوم الجمعة",
        "used_time_now_saturday": "السبت هو بداية مغامرات جديدة.",
        "used_time_now_sunday": "واصل السعي نحو أهدافك.",
        "used_time_now_monday": "استمر في الزخم والإيجابية.",
        "used_time_now_tuesday": "اشحن نفسك واستعد لما هو قادم.",
        "used_time_now_wednesday": "أنهِ ما تبقى من عمل الأسبوع واستمتع بوقتك الباقي.",
        "used_time_now_thursday": "حان وقت الاستمتاع بالجهود المبذولة.",
        "used_time_now_friday": "الاسترخاء والاستمتاع، استمتع بلحظات الهدوء.",
        "fuzzy_time_thursday": "الخميس هو وقتك الخاص، استمتع بكل لحظة وافعل ما تريد.",
        "music_player": "مشغل الموسيقى",
        "music_player_no_artist": "لا يوجد فنان",
        "music_player_no_title": "لا يوجد عنوان",
        "music_player_no_music_playing": "لا توجد موسيقى قيد التشغيل",
        # Hardware
        "cpu_usage": "مستهلك من المعالج",
        "ram_usage": "مستهلك من الرام",
        "battery_percentage": "نسبة البطارية",
        "high_wifi_temp_warning": "تحذير: درجة حرارة الواي فاي مرتفعة جداً",
        "high_wifi_temp_message": "درجة حرارة جهاز الواي فاي مرتفعة (${wifiTemp}°C) وقد تؤدي إلى أداء غير مستقر أو تلف الأجهزة. يرجى التحقق من تهوية الجهاز والتأكد من عدم وجود مشكلات في التبريد.",
        "high_nvme_temp_warning": "تحذير: درجة حرارة NVMe مرتفعة جداً",
        "high_nvme_temp_message": "درجة حرارة NVMe مرتفعة (${nvmeTemp}°C) وقد تؤدي إلى أداء غير مستقر أو تلف الأجهزة. يرجى التحقق من تهوية الجهاز والتأكد من عدم وجود مشكلات في التبريد.",
        "high_cpu_temp_warning": "تحذير: درجة حرارة المعالج المركزي مرتفعة جداً",
        "high_cpu_temp_message": "درجة حرارة المعالج المركزي مرتفعة (${cpuTemp}°C) وقد تؤدي إلى أداء غير مستقر أو تلف الأجهزة. يرجى التحقق من تهوية الجهاز والتأكد من عدم وجود مشكلات في التبريد.",
        "device_temp_total": "اجمالي درجة حرارة الاجهزة",
        "battery": "البطارية",
        "battery_health": "الصحة",
        "battery_voltage": "الفولتية",
        "battery_energy": "الطاقة",
        "battery_cycles": "الدورات",
        "high_voltage_warning": "تحذير: فولتية مرتفعة جداً",
        "high_voltage_message": "جهازك يستخدم شاحن بفولتية (${voltage} V) أعلى من المتوقع (${highVoltage} V). قد يؤدي ذلك إلى تلف البطارية أو الدوائر الإلكترونية. يرجى استخدام شاحن مناسب لجهازك.",
        "high_performance": "عالي",
        "balanced": "متوازن",
        "power_saver": "منخفض",
        "power_profile": "وضع الاداء",
        "devices_temp": "حرارة الاجهزة",
        "wifi_temp": "الوايفاي",
        "nvme_temp": "الهارد",
        "cpu_temp": "المعالج",
        "process": "العملية",
        "percentage": "%",
        "volume_level": "مستوى الصوت",
        "brightness_level": "مستوى السطوع",
        "battery_percentage": "نسبة البطارية",
        "hardware_temperature": "اجمالي درجة حرارة الاجهزة",
        "media_center": "مركز الوسائط",
        "control_center": "مركز التحكم",
        "hardware_center": "مركز العتاد",
        "do_you_want_to_poweroff": "هل تريد ايقاف التشغيل ؟",
        "do_you_want_to_restart": "هل تريد اعادة التشغيل ؟",
        "do_you_want_to_logout": "هل تريد تسجيل الخروج ؟",
        "yes": "نعم",
        "no": "لا",
        "control_tab": "التحكم",
        "notifications_tab": "اشعارات",
        "weather_tab": "الطقس",
        "monitors_tab": "مؤشرات",
        "calender_tab": "التقويم",
        "network_tab": "الشبكة",
        "delete_all": "حذف الكل",
        "notification_count_text": "اشعار",
        "themes": "السمات",
        "cpu": "المعالجة",
        "ram": "الذاكرة",
        "temp": "الحرارة",
        "high_cpu_usage_title": "استخدام عالي للمعالج",
        "high_cpu_usage_message": "العملية ${process} تستخدم ${percentage}% من المعالج",
        "show_desktop_widgets": "عرض ادوات سطح المكتب",
    },
    "en": {
        "hello": "Hello",
        "today": "Today",
        "tomorrow": "Tomo..",
        "day_after_tomorrow": "D-A-T",
        "no_notifications": "No new notifications",
        "notification_center": "Notification Center",
        # Themes
        "black_hole_theme": "B-Hole",
        "deer_theme": "Deer",
        "color_theme": "Aest ..",
        "siberian_theme": "Sibe ..",
        "material_you_theme": "M-You",
        "win20_theme": "Win 20",
        "game_theme": "Game",
        "dark_theme": "Dark",
        "unicat_theme": "Unicat",
        "new_cat_theme": "N-Cat",
        "golden_theme": "Golden",
        "harmony_theme": "Harm ..",
        "circles_theme": "Circles",
        "white_flower": "Flo ..",
        # Circles Widget
        "linux_title": "Linux",
        "system_title": "System",
        "name_title": "Name",
        "host_title": "Host",
        "runtime_title": "Runtime",
        "package_manager_title": "Package Manager",
        "packages_title": "Packages",
        "weather_not_available": "Weather not available",
        # Prayers
        "prayer_times": "Prayer Times",
        "fajr_prayer": "Fajr Prayer",
        "dhuhr_prayer": "Dhuhr Prayer",
        "asr_prayer": "Asr Prayer",
        "maghrib_prayer": "Maghrib Prayer",
        "isha_prayer": "Isha Prayer",
        "prayer_time_now": "It is now time for",
        "fajr": "Fajr",
        "isha": "Isha",
        "maghrib": "Maghrib",
        "asr": "Asr",
        "dhuhr": "Dhuhr",
        # Weather
        "feels_like": "Feels Like",
        "humidity": "Humidity",
        "max_temp": "Max temp",
        "min_temp": "Min temp",
        "pressure": "Pressure",
        "wind": "Wind",
        "clouds": "Clouds",
        "min_and_max": "Min and Max",
        "cold_weather": "Cold Weather!",
        "hot_weather": "Hot Weather!",
        "rainy_weather_title": "Rainy weather",
        "rainy_weather_text": "Chance of rain is",
        "min_temperature": "Today's minimum temperature",
        "max_temperature": "Today's maximum temperature",
        "sunset": "Sunset",
        "sunrise": "Sunrise",
        # Fuzzy Widget
        "fuzzy_clock_thursday": "Welcome Thursday!",
        "fuzzy_clock_programming_time": "It is programming time, the time for creativity!",
        "fuzzy_clock_morning": "Good morning! A new day full of opportunities begins",
        "fuzzy_clock_coffee": "With a cup of coffee, let the achievements begin",
        "fuzzy_clock_lunch": "It’s lunchtime, take a break and get ready for the second round",
        "fuzzy_clock_creative": "It’s time for creativity, passion and light work await you",
        "fuzzy_clock_tea": "Enjoy a cup of tea and relax with a light book",
        "fuzzy_clock_dinner": "Dinner is ready, enjoy your time with your loved ones",
        "fuzzy_clock_night": "Good night! Relax and get ready for a new day",
        "fuzzy_clock_play": "Have fun and enjoy, it’s the holiday!",
        "fuzzy_clock_pray": "Perfect time for prayers and reading Quran",
        "fuzzy_clock_bath": "Shower and get ready for the blessed Friday prayer",
        "fuzzy_clock_friday_prayer": "It’s time for Friday prayer",
        "fuzzy_clock_family": "Enjoy lunch with the family and relax",
        "fuzzy_clock_friends": "Go out with friends and enjoy your day",
        "fuzzy_clock_relax": "Good night! Relax and get ready for a new day",
        "fuzzy_day_saturday": "Welcome to a new day,",
        "fuzzy_day_sunday": "Sunday is a new opportunity",
        "fuzzy_day_monday": "Half of the week has come",
        "fuzzy_day_tuesday": "A day full of tasks",
        "fuzzy_day_wednesday": "Today is Wednesday,",
        "fuzzy_day_friday": "Friday",
        "used_time_now_saturday": "Saturday is the start of new adventures.",
        "used_time_now_sunday": "Keep striving towards your goals.",
        "used_time_now_monday": "Keep up the momentum and positivity.",
        "used_time_now_tuesday": "Recharge and prepare yourself for what’s ahead.",
        "used_time_now_wednesday": "Finish what’s left of the week’s work and enjoy the rest of your time.",
        "used_time_now_thursday": "Time to enjoy the efforts put in.",
        "used_time_now_friday": "Relaxation and enjoyment, enjoy the moments of calm.",
        "fuzzy_time_thursday": "Thursday is your special time, enjoy every moment and do what you want.",
        "music_player": "Music Player",
        "music_player_no_artist": "No artist",
        "music_player_no_title": "No title",
        "music_player_no_music_playing": "There is no music currently playing.",
        # Hardware
        "cpu_usage": "CPU Usage",
        "ram_usage": "RAM Usage",
        "battery_percentage": "Battery Percentage",
        "high_wifi_temp_warning": "Warning: High Wi-Fi Temperature",
        "high_wifi_temp_message": "The temperature of the Wi-Fi device is high (${wifiTemp}°C) and may lead to unstable performance or hardware damage. Please check the device's ventilation and ensure there are no cooling issues.",
        "high_nvme_temp_warning": "Warning: High NVMe Temperature",
        "high_nvme_temp_message": "The temperature of NVMe is high (${nvmeTemp}°C) and may lead to unstable performance or hardware damage. Please check the device's ventilation and ensure there are no cooling issues.",
        "high_cpu_temp_warning": "Warning: High CPU Temperature",
        "high_cpu_temp_message": "The temperature of the CPU is high (${cpuTemp}°C) and may lead to unstable performance or hardware damage. Please check the device's ventilation and ensure there are no cooling issues.",
        "device_temp_total": "Total Device Temperature",
        "battery": "Battery",
        "battery_health": "Health",
        "battery_voltage": "Voltage",
        "battery_energy": "Energy",
        "battery_cycles": "Cycles",
        "high_voltage_warning": "Warning: High Voltage",
        "high_voltage_message": "Your device is using a charger with voltage (${voltage} V) higher than expected (${highVoltage} V). This could lead to battery or circuitry damage. Please use a compatible charger for your device.",
        "high_performance": "High",
        "balanced": "Balanced",
        "power_saver": "Low",
        "power_profile": "Power Profile",
        "devices_temp": "Devices Temperature",
        "wifi_temp": "Wi-Fi",
        "nvme_temp": "NVMe",
        "cpu_temp": "CPU",
        "process": "Process",
        "percentage": "%",
        "volume_level": "Volume Level",
        "brightness_level": "Brightness Level",
        "hardware_temperature": "Hardware Temperature",
        # audio
        "media_center": "Media Center",
        "control_center": "Media Center",
        "hardware_center": "Hardware Center",
        "do_you_want_to_poweroff": "Do you want to power off ?",
        "do_you_want_to_restart": "Do you want to restart ?",
        "do_you_want_to_logout": "Do you want to logout ?",
        "yes": "Yes",
        "no": "No",
        "control_tab": "Control",
        "notifications_tab": "Notifications",  # truncateString('Notifications', 8),
        "weather_tab": "Weather",  # truncateString('Weather', 9),
        "monitors_tab": "Monitors",  # truncateString('Monitors', 9),
        "calender_tab": "Calender",  # truncateString('Calender', 9),
        "network_tab": "Network",
        "delete_all": "Delete all",
        "notification_count_text": "Notification",
        "themes": "Themes",
        "cpu": "CPU",
        "ram": "RAM",
        "temp": "TEMP",
        "high_cpu_usage_title": "High CPU usage",
        "high_cpu_usage_message": "The process ${process} is using ${percentage}% of total CPU",
        "show_desktop_widgets": "Show Desktop Widgets",
    },
}


selected_strings = strings["ar"] if local == "RTL" else strings["en"]


def get_string(key):
    """Retrieves a string based on the key.  Returns the key if not found."""
    return selected_strings.get(key, key)
