local = "RTL"

strings = {
    "ar": {
        "today": "اليوم",
        "hello": "مرحبا",
        "tomorrow": "غدا",
        "dayAfterTomorrow": "ب غدا",
        "noNotifications": "لا توجد أي إشعارات جديدة",
        "notificationCenter": "مركز الإشعارات",
        # Themes
        "blackHoleTheme": "ثقب",
        "deerTheme": "غزال",
        "colorTheme": "جمالي",
        "siberianTheme": "تدرج",
        "materialYouTheme": "مادي",
        "win20Theme": "ويندوز",
        "gameTheme": "لعبة",
        "darkTheme": "مظلم",
        "unicatTheme": "قط",
        "newCatTheme": "قط 2",
        "goldenTheme": "ذهبي",
        "harmonyTheme": "تناغم",
        "circlesTheme": "دوائر",
        "whiteFlower": "ابيض",
        # Circles Widget
        "linuxTitle": "لينكس",
        "systemTitle": "النظام",
        "nameTitle": "الاسم",
        "hostTitle": "الهوست",
        "runtimeTitle": "وقت التشغيل",
        "packageManagerTitle": "مدير الحزم",
        "packagesTitle": "الحزم",
        # Prayers
        "prayerTimes": "اوقات الصلوات",
        "fajrPrayer": "صلاة الفجر",
        "dhuhrPrayer": "صلاة الظهر",
        "asrPrayer": "صلاة العصر",
        "maghribPrayer": "صلاة المغرب",
        "ishaPrayer": "صلاة العشاء",
        "prayerTimeNow": "حان الآن وقت صلاة",
        "fajr": "الفجر",
        "isha": "العشاء",
        "maghrib": "المغرب",
        "asr": "العصر",
        "dhuhr": "الظهر",
        # Weather
        "feelsLike": "شعور وكانة",
        "humidity": "الرطوبة",
        "pressure": "الضغط",
        "maxTemp": "العليا",
        "minTemp": "الصغرى",
        "wind": "الرياح",
        "clouds": "السحب",
        "minAndMax": "الصغرى والعلياء",
        "coldWeather": "طقس بارد !",
        "hotWeather": "طقس حار !",
        "rainyWeatherTitle": "جو ممطر",
        "rainyWeatherText": "من المتوقع هطول الامطار اليوم بنسبة",
        "minTemperature": "درجة الحرارة الصغرى اليوم",
        "maxTemperature": "درجة الحرارة الكبرى اليوم",
        "weatherNotAvailable": "خدمة الطقس غير متاحة",
        "sunset": "الغروب",
        "sunrise": "الشروق",
        # Add all remaining keys here
    },
    "en": {
        "hello": "Hello",
        "today": "Today",
        "tomorrow": "Tomo..",
        "dayAfterTomorrow": "D-A-T",
        "noNotifications": "No new notifications",
        "notificationCenter": "Notification Center",
        # Themes
        "blackHoleTheme": "B-Hole",
        "deerTheme": "Deer",
        "colorTheme": "Aest ..",
        "siberianTheme": "Sibe ..",
        "materialYouTheme": "M-You",
        "win20Theme": "Win 20",
        "gameTheme": "Game",
        "darkTheme": "Dark",
        "unicatTheme": "Unicat",
        "newCatTheme": "N-Cat",
        "goldenTheme": "Golden",
        "harmonyTheme": "Harm ..",
        "circlesTheme": "Circles",
        "whiteFlower": "Flo ..",
        # Circles Widget
        "linuxTitle": "Linux",
        "systemTitle": "System",
        "nameTitle": "Name",
        "hostTitle": "Host",
        "runtimeTitle": "Runtime",
        "packageManagerTitle": "Package Manager",
        "packagesTitle": "Packages",
        "weatherNotAvailable": "Weather not available",
        # Add all remaining keys here
    },
}

selected_strings = strings["ar"] if local == "RTL" else strings["en"]
