import { local } from '../utils/helpers.js';
import { Widget } from '../utils/imports.js';

const wordsDictAr = [
    'لِتبرَأ الرُّوح مِن ضِيقٍ ومِن كَدَرٍ - ويَبْرأ الجِسْمُ مِن وَهْنٍ ومِن سَغَبِ',
    'لَكَم نُغالِبُ في الأيّامِ مِن كَبَدٍ - نَظُنُّ أنّ هَنَاء العَيْشِ في الغَلَبِ',
    'إلى حتفي مَشَتْ قدمي.',
    'اليوم خمر وغداً أمر.',
    'تجري الرياح بما لا تشتهي السفن.',
    'حنانيك بعض الشر أهون من بعض.',
    'رُبَّ دهر بكيت منه فلما صرت في غيره بكيت عليه.',
    'رُبَّ ملوم لا ذنب له.',
    'قُتل رحمه الله” خير من “فر أخزاه الله”.',
    'أخاك أخاك إن مَنْ لا أخاً له كَساعٍ إلى الهيجا بغير سلاح.',
    'أخوك من صدقك النصيحة.',
    'إذا غامَرْتَ في شرف مروم فلا تقنع بما دون النجوم.',
    'إذا لم يكن إلا الأَسِنَّةُ مركباً فلا رأي للمضطر إلا ركوبها.',
    'السعادة والرضا أدوات تجميل عظيمة، وأدوات خادعة لحفظ مظهر الشباب.',
    'تزيين الجسم أسرع من تزيين النفس.',
    'ليست البقرة الأقوى خواراً، هي البقرة الأكثر مدراراً.',
    'من لا يعرف التصنع لا يعرف العيش.',
    'ما فائدة الدنيا الواسعة، إذا كان حذاؤك ضيقاً.',
    'الدعوة للحرية ليس معناها دعوة للإنفلات والفوضى والهمجية الحرية قيمة عظيمة ولكن القاعدة: أنت حر ما لم تضر.',
    'إذا كانت الحرية ضعيفة التسليح فعلينا تسليحها بقوة الارادة.',
    'استقبال الموت خير من استدباره.',
    'أكرم نفسك عن كل دنيء.',
    'الإفراط في التواضع يجلب المذلة.',
    'الجود بالنفس أقصى غاية الجود.',
    'السيف أهول ما يُرى مسلولاً.',
    'العز في نواصي الخيل.',
    'القَصَّابُ لا تهوله كثرة الغنم.',
    'إن البعوضة تُدْمي مُقْلةَ الأسد.',
    'إن الجبان حتْفُه من فوقه.',
    'إن القذى يؤذي العيون قليله ولربما جرح البعوض الفيلا.',
    'أنا لها ولكل عظيمة.',
    'بنفسي فَخَرْتُ لا بجدودي.',
    'تجوع الحرة ولا تأكل بثدييها.',
    'تعدو الذئاب على من لا كلاب له وتتقي صولة المستنفر الحامي.',
    'ذل من لا سيف له.',
    'عش عزيزاً أو مت وأنت كريم.',
    'رُبَّ نعل شر من الحفا.',
    'سحابة صيف تذروها الرياح عند الصباح يحمد القوم السرى.',
    'في فمي ماء وهل ينطق من في فمه ماء.',
    'لا تشكون إلى خلق فتشمته شكوى الجريح إلى الغربان والرخم.',
    'فرخ البط عوام.',
    'من شابه أباه فما ظلم.',
    'هذا الشبل من ذاك الأسد.',
    'كلما ارتفع الشريف تواضع، وكلما ارتفع الوضيع تكبر.',
    'لا حسب كالتواضع ولا شرف كالعلم.',
    'إذا وجد المؤمن الصحيح وجدت معه أسباب النجاح جميعاً.',
    'المؤمن إذا جاع صبر وإذا شبع شكر.',
    'المؤمن غر كريم والفاجر خب لئيم.',
    'يجب أن أخترع نظاماً وإلا فسيستعبدني نظام رجل أخر.',
    'حيث النظام نجد الطعام حيث الفوضى تجد الجوع.',
    'أفضل وسيلة لتدمير النظام الرأسمالي هو إفساد قيمة المال.',
    'الأدارة تعمل من خلال النظام أما القيادة فتعمل فوق النظام.',
    'الزينة الجميلة تغطي لحماً هزيلاً.',
    'ليست الحرية غياب الالتزامات انما هي القدرة على أختيار ما هو أفضل لي وإلزام نفسي به.',
    'الحياة ليست عادلة، فلتعود نفسك على ذلك.',
    'في المدرسة يعلمونك الدرس ثم يختبرونك، أما الحياة فتختبرك ثم تعلمك الدرس.',
    'لا تكن رأساً فالرأس كثير الأذى.',
    'لا كرامة لنبيّ في وطنه.',
    'إذا أنت لم تشرب مراراً على القذى ظمئت وأي الناس تصفو مشاربه.',
    'إذا كان الصبر مُرًّاً فعاقبته حلوة.',
    'اصبر تنل.',
    'اصبر قليلاً فبعد العسر تيسير وكل أمر له وقت وتدبير.',
    'اصبر لكل مُصِيبةٍ وتجلًّدِ واعلم بأن الدهر غير مُخَلَّدِ.',
    'الأيام دول. التأني من الرحمن والعجلة من الشيطان.',
    'الجزع عند المصيبة مصيبة.',
    'الرمد أهون من العمى.',
    'الصبر صبران: صبر على ما تكره وصبر على ما تحب.',
    'الصبر عند الصدمة الأولى.',
    'الصبر مفتاح الفرج.',
    'إن السماء تُرْجَى حين تحتجب.',
    'إن الله يمهل ولا يهمل.',
    'إن غداً لناظره قريب.',
    'إن مع اليوم غداً يا مسعدة.',
    'أنا الغريق فما خوفي من البلل. بالتأني تُدْرَكُ الفُرَصُ.',
    'لكل حي أجل.',
    'لكل داء دواء.',
    'إذا ذكرت الذئب فخذ الحذر.',
    'آخر الحياة الموت.',
    'إذا قل ماء الوجه قل حياؤه، ولا خير في وجه إذا قل ماؤه.',
    'إذا حان القضاء ضاق الفضاء.',
    'إذا سلمت من الأسد فلا تطمع في صيده.',
    'إذا ظلمت من دونك فلا تأمن عقاب من فوقك.',
    'إذا قصرت يدك عن المكافأة فليصل لسانك بالشكر.',
    'إذا كان الكلام من فضة فالسكوت من ذهب.',
    'بعض الحلم ذل.',
    'يد واحدة لا تحمل بطيختين.',
    'خذوا الحكمة من أفواه البسطاء.',
    'ما كلُّ ما يُعلم يُقال.',
    'اجلس حيث يُؤْخَذُ بيدك وَتُبَرُّ ولا تجلس حيث يؤخذ برجلك وتُجَرُّ.',
    'أَحْسِنْ إلى الناس تستعبد قلوبهم. إذا تم العقل نقص الكلام.',
    'كل غريب للغريب نسيب.',
    'ابذل لصديقك دمك ومالك.',
    'غبن الصديق نذالة.',
    'احذر عدوك مرة وصديقك ألف مرة فإن انقلب الصديق فهو أعلم بالمضرة.',
    'آخ الأْكْفاءَ وداه الأعداء.',
    'أخوك من صَدَقك لا من صدّقك.',
    'خير الإخوان أقدمهم.',
    'إذا صُنْتَ المودة كان باطنها أحسن من ظاهرها.',
    'إذا كنت في كل الأمور معاتباً صديقك لم تلق الذي لا تعاتبه.',
    'اعرف صاحبك واتركه.',
    'الإمارة حلوة الرضاع مُرَّةُ الفطام.',
    'الجار أولى بالشُّفْعَةِ.',
    'الجار قبل الدار.',
    'الصديق إما أن ينفع وإما أن يشفع.',
    'الصديق وقت الضيق.',
    'العتاب هدية الأحباب.',
    'الغائب عُذْرُه معه.',
    'في سعة الأخلاق كنوز الأرزاق.',
    'كن مخلصاً في عملك تبلغ أقصى أملك.',
    'الغريق يتمسك بقشة.',
    'أنفق ما في الجيب، يأتيك ما في الغيب.',
    'من أدب ولده صغيراً سر به كبيراً.',
    'أجلد السرج لكي تحمل الحمار على التفكير.',
    'من أنهكني علمني القوة.',
    'من شب على شيء شاب عليه.',
    'في التأني السلامة وفي العجلة الندامة.',
    'العجول مخطيء ولو ملك، والمتأني مصيب وإن هلك.',
    'من أسرع كثر عثاره.',
    'من تأنى نال ما تمنى.',
    'الخطأ زاد العجول.',
    'بالتأني تسهل المطالب.',
    'من ركب العجلة أدركه الزلل.',
    'ما طار طير وارتفع إلا كما طار وقع.',
    'لا يتكبر إلا كل وضيع، ولا يتواضع إلا كل رفيع.',
    'اللهم قني شر أصدقائي أما أعدائي فأنا كفيل بهم.',
    'الناس لبعضها.',
    'الوَحْدَةُ خير من جليس السوء.',
    'إن أخاك من واساك.',
    'إذا زل العالِمُ زل بزلته عالَمٌ.',
    'إذا ضربت فأوجع فإن الملامة واحدة.',
    'إذا كنت ذا رأي فكن ذا عزيمة.',
    'إذا نُصِرَ الرأي بطل الهوى.',
    'أرسل حكيماً ولا توصه.',
    'اشتدي يا أزمة تنفرجي.',
    'أشد الجهاد مجاهدة الغيظ.',
    'أشد الفاقة عدم العقل.',
    'السعادة صحة جيدة وذاكرة سيئة.',
    'اخطب لبنتك ولا تخطب لابنك.',
    'أكبر منك بيوم يعرف عنك بسنة.',
    'الأم مدرسة إذا أعددتها أعددت شعباً طيب الأعراق.',
    'البطن لا تلد عدواً.',
    'التجارب ليست لها نهاية والمرء منها في زيادة.',
    'التجربة العلم الكبير.',
    'العبد يقرع بالعصا والحر تكفيه الإشارة.',
    'العتب على النظر.',
    'العلم زين فكن للعلم مكتسباً وكن له طالبًا ما عشت مقتبسا.',
    'العلم يجدي ويبقى للفتى أبدا والمال يفنى وإن أجدى إلى حين.',
    'العلم يرفع بيتاً لا عماد له والجهل يهدم بيت العز والشرف.',
    'القرد في عين أمه غزال.',
    'الكتاب يقرأ من عنوانه.',
    'إذا دببت على المنسأة من هرم فقد تباعد عنك اللهو والغزل.',
    'إذا عُرِفَ السبب بطل العجب.',
    'وإذا كانت النفوس كباراً تعبت في مرادها الأجسام.',
    'اطلب من العلوم علماً ينفعك ينفي الأذى والعيب ثم يرفعك.',
    'أعدل الشهود التجارب.',
    'أعز من الولد ولد الولد.',
    'أعز مكان في الدنا سرج سابح وخير جليس في الزمان كتاب.',
    'خادم سيدين يكذب على أحدهما.',
    'إذا سمعت الرجل يقول فيك من الخير ما ليس فيك فلا تأمن أن يقول فيك من الشر ما ليس فيك.',
    'أذل البخل أعناق الرجال.',
    'أرى كل إنسان يرى عيب غيره ويعمى عن العيب الذي هو فيه.',
    'أساء سمعاً فأساء إجابة.',
    'أسد عليَّ وفي الحروب نعامة.',
    'أعلمه الرماية كل يوم فلما أشتد ساعِدُهُ رماني.',
    'أغنى الأغنياء من لم يكن للبخل أسيراً.',
    'آفة الحديث الكذب. أقل الناس سروراً الحسود.',
    'أكلوا خيري وعصوا أمري.',
    'البخيل عظيم الرواق صغير الأخلاق.',
    'البخيل غناه فقر ومطبخه قفر.',
    'البخيل لا تَبُلُّ إحدى يديه الأخرى.',
    'اجتنب مصاحبة الكذاب فإن اضطررت إليه فلا تُصَدِّقْهُ.',
    'أجهل الناس من كان على السلطان مدلاً وللإخوان مذلاً.',
    'أحضر الناس جواباً من لم يغضب.',
    'اختلط حابلهم بنابلهم.',
    'إذا تفرقت الغنم قادتها العنز الجرباء.',
    'إذا ساء فعل المرء ساءت ظنونه وَصَدَّقَ ما يعتاده من توهم.',
    'إذا سأل ألحف وإن سئل سوّف.',
    'احفر بئراً وَطُمَّ بئراً ولا تُعَطِّلْ أجيرا.',
    'احفظ قرشك الأبيض ليومك الأسود.',
    'إذا كنت سنداناً فاصبر وإذا كنت مطرقة فأوجع.',
    'إذا هَبَّتْ رياحك فاغتنمها.',
    'استر عورة أخيك لما يعلمه فيك.',
    'اشكر من أَنْعَمَ عليك وأَنْعِمْ على من شكرك.',
    'اِضْرِبْ ما دام الحديد حامياً.',
    'اعقلها وتوكل.',
    'اعمل الطيب وارمه البحر.',
    'أفضل الجود أن تبذل من غير مسألة.',
    'أقلل عتابك فالبقاء قليل والدهر يعدل تارة ويميل.',
    'وانهض فوراً مستبشراً ، فتلك هي أولى درجات النجاح.',
    'عندما يرن الهاتف ابتسم وأنت تتلقى السماعة، فإن محدثك على الطرف الآخر سيرى ابتسامتك من خلال نبرات صوتك.',
    'تزوج من تجيد المحادثة، فعندما يتقدم بك العمر ستعرف أهمية ذلك، عندما يصبح الحديث مع من تحب قمة أولوياتك واهتماماتك.',
    'إذا أحببت شخصاً فاذهب إليه وقل إنك تحبه ، إلّا إذا كنت لا تعني ما تقول فعلاً ! لأنه سيعرف الحقيقة بمجرد النظر في عينيك.',
    'لا تتردد في أن تتأسف لمن أخطأت في حقه ، وانظر لعينيه وأنت تنطق بكلمات الاعتذار ، ليقرأها في عينيك وهو يسمعها بأذنيه.',
    'لا تحكم على شخص من أقربائه فقط ، فالإنسان لم يختر والديه ، فما بالك بأقربائه.',
    'عندما لا تريد الإجابة على سؤال ، فابتسم للسائل قائلاً: هل تعتقد أنه فعلاً من المهم.',
    'لا تدع الأشياء الصغيرة تدمر صداقتك الغالية مع الآخرين ، فالصداقة الحقيقية تاج على رؤوس البشر ، لا يدركه إلا سكان الجدران الخالية والقلوب الخاوية.',
    'لا تسخر من الآخرين وأحلامهم الوردية الجميلة ، خاصة من تعتقد أنهم أقل منك من البسطاء الطيبين ، فلربما تكون منزلة خادمك عند الله أسمى وأرفع منك ومن كثير من علياء القوم ، وقد تحظى بشفاعتهم يوم القيامة، ولا تقلل من شأن الأحلام ، فالدنيا بدونها رحلة جافة ومملة مهما يكن الواقع جميلا.',
    'فكر كثيراً ، واستنتج طويلا ، وتحدث قليلاً، ولا تهمل كل ما تسمعه ! فمن المؤكد أنك ستحتاجه في المستقبل.',
    'من يغرق يتعلق بعود قش.',
    'أعزب دهر ولا أرمل شهر.',
    'اعطني عمر وارميني بالبحر.',
    'ألا كل ما هو آت قريب وللأرض من كل حي نصيب.',
    'الحصاة من الجبل.',
    'الصباح رباح.',
    'العمر واحد والرب واحد.',
    'المأمول خير من المأكول.',
    'أول الشجرة بذرة.',
    'البعيد عن العين بعيد عن القلب.',
    'الحب أعمى.',
    'من أحب ولده رحم الأيتام.',
    'القلوب عند بعضها.',
    'إن العيون التي في طرفها حور قتلننا ثم لم يحيين قتلانا يَصرَعْنَ ذا اللب حتى لا حراك به وهن أضعف خلق الله إنسانا.',
    'أول الشجرة بذرة.',
    'ربك رب قلوب.',
    'فإن قليل الحب بالعقل صالح وإن كثير الحب بالجهل فاسد.',
    'لا تخف ما صنعت بك الأشواق .. واشرح هواك فكلنا عشاق.',
    'مرآة الحب عمياء.',
    'من القلب للقلب رسول.',
    'رب بعيد أنفع من قريب.',
    'فيا ليت الشباب يعود يوماً فأخبره بما فعل المشيب.',
    'كلكم طلب صيد.',
    'ما أبعد ما فات وما أقرب ما يأتي.',
    'ما كل ما يتمنى المرء يدركه تجرى الرياح بما لا تشتهي السفن.',
    'كل حبل على غاربه.',
    'ما أشبه الليلة بالبارحة.',
    'أثقل من جبل.',
    'أحذر من غراب.',
    'أحرس من كلب.',
    'أدنى من حبل الوريد.',
    'أرخص من التمر في البصرة.',
    'أسرع من الريح.',
    'أقرب من اللسان للأسنان.',
    'البعد جفاء.',
    'البياض نصف الحسن.',
    'الماء أهون موجود وأعز مفقود.',
    'المتكبر كالواقف على الجبل يرى الناس صغاراً ويرونه صغيراً.',
    'أتبع من الظل.',
    'إنه أشبه به من التمرة بالتمرة.',
    'سارت به الرُّكْبانُ.',
    'عاد الأمر إلى نصابه.',
    'فالوجه مثل الصبح مبيض والشعر مثل الليل مسود.',
    'فما تحمد العينان كل بشاشة ولا كل وجه عابس بذميم.',
    'لسان المرء من خدم الفؤاد.',
    'صاحب الحق عينه قوية.',
    'على الباغي تدور الدوائر.',
    'كما تدين تدان.',
    'لا يَفُلُّ الحديد إلا الحديد.',
    'من عَفَّ عن ظلم العباد تورعاً جاءته ألطاف الإله تبرعا.',
    'هذه بتلك والبادئ أظلم.',
    'هي النفس ما حَمَّلْتَها تتحمل وللدهر أيام تجور وتَعْدِلُ.',
    'ما أشبه الليلة بالبارحة.',
    'من يخشى البلل لا يصطاد السمك.',
    'معظم النار من مستصغر الشرر.',
    'اترك الشر يتركك.',
    'احذر الأحمق واحذر وُدَّهُ إنما الأحمق كالثوب الْخَلَق.',
    'احذروا من لا يرجى خيره ولا يؤمن شره.',
    'إذا جاء الحين حارت العين.',
    'إذا ذكرت الذئب فأعد له العصا.',
    'إذا رأيت نيوب الليث بارزة فلا تظنن أن الليث يبتسم.',
    'إذا كنتَ ذا رأىٍ فكن ذا مشورة فإن فساد الرأي أن تترددا.',
    'أعدّوا لكلب السوء كلباً يعادله.',
    'أقلل طعامك تجد منامك.',
    'الدهر يومان حلو ومر.',
    'اللي يخاف من العفريت يطلع له.',
    'إن الجواد قد يعثر.',
    'إن الشفيق بسوء ظن مولع.',
    'إن كنت ريحاً فقد لاقيت إعصارا.',
    'إن وراء الأَكَمةِ ما وراءها.',
    'خُذْهُ بالموت حتى يرضى بالحُمَّى.',
    'راحت السكرة وجاءت الفكرة.',
    'ستبدي لك الأيام ما كنت جاهلاً.',
    'قد يخرج من الصدفة غير الدُّرَّة.',
    'أَدّى قدراً مستعيرها.',
    'إذا أتاك أحد الخصمين وقد فُقِئَتْ عينه فلا تقض له حتى يأتيك خصمه فلعله قد فُقِئَتْ عيناه.',
    'إذا تولى عقداً أحكامه.',
    'الجزاء من جنس العمل.',
    'الحق دولة والباطل جولة.',
    'الرجوع إلى الحق خير من التمادي في الباطل.',
    'العاقل لا يبطل حقاً ولا يحق باطلاً.',
    'العدل أساس الْمُلْك.',
    'العين بالعين والسن بالسن.',
    'إذا أردت أن تطاع فأمر بما يستطاع.',
    'إذا المرء لم يدنس من اللؤم عرضه فكل رداء يرتديه جميل.',
    'إذا أنت أكرمت الكريم ملكته وإن أنت أكرمت اللئيم تمردا.',
    'كفى المرء فضلاً أن تُعَدَّ معايبه.',
    'إذا حضر الماء بطل التيمم.',
    'اذالم تستحي فأفعل ما تشاء.',
    'أطهر الناس أعراقاً أحسنهم أخلاقاً.',
    'أعرف الناس بالله أرضاهم بما قسم الله له.',
    'اعف عما أغضبك لما أرضاك.',
    'أفضل الجود العطاء قبل الموعد.',
    'الْبِشْرَ دال على الكرم.',
    'التكبر على المتكبر تواضع.',
    'التواضع من مصائد الشرف.',
    'الجودة من الموجودة.',
    'الحر تكفيه الإشارة.',
    'الحِلْمُ سيد الأخلاق.',
    'الدال على الخير كفاعله.',
    'الرفق بالجاني عتاب.',
    'السر أمانة.',
    'الشريف إذا تَقَوَّى تواضع والوضيع إذا تَقَوَّى تكبر.',
    'الناس الذين غيروا العالم هم الناس الذين واصلوا البحث عندما بدا الأمر مستحيلاً بالنسبة للآخرين.',
];

const wordsDictEn = [
    'Let the soul heal from distress and sorrow - and the body heal from weakness and hunger.',
    'How much we struggle in life - thinking happiness comes from overcoming.',
    'To my fate my feet have walked.',
    'Today is wine and tomorrow is another matter.',
    'Winds blow counter to what ships desire.',
    'Some evil is lesser than other evil.',
    'There were times I cried and later wished for those times back.',
    'Often blamed without fault.',
    'Killed, may God have mercy on him, is better than escaped, may God disgrace him.',
    'Your brother, your brother; without a brother, it’s like going to battle without a weapon.',
    'Your brother is the one who gives you sincere advice.',
    'If you venture in honor, don’t settle for less than the stars.',
    'If only spears are left, the compelled has no choice but to ride them.',
    'Happiness and contentment are great cosmetics, and deceptive tools to keep youth’s appearance.',
    'Beautifying the body is faster than beautifying the soul.',
    'It’s not the cow that moos the most that gives the most milk.',
    'Those who don’t know pretense don’t know how to live.',
    'What good is a wide world if your shoes are tight?',
    'Calling for freedom does not mean calling for anarchy and chaos; freedom is a great value, but the rule is: you are free as long as you don’t harm others.',
    'If freedom is weakly armed, we must arm it with strong will.',
    'Facing death is better than fleeing from it.',
    'Honor yourself from every lowly act.',
    'Excessive humility brings humiliation.',
    'The greatest generosity is sacrificing oneself.',
    'The sword is most terrifying when drawn.',
    'Honor lies in the forelocks of horses.',
    'The butcher is not daunted by many sheep.',
    'Even a mosquito can bleed a lion’s eye.',
    'The coward’s fate is from above him.',
    'A speck of dust hurts the eye, and a mosquito can wound an elephant.',
    'I’m ready for it and for every great task.',
    'I take pride in myself, not in my ancestors.',
    'A free woman would rather starve than eat from her own breasts.',
    'Wolves attack those without dogs and fear the vigilant protector.',
    'He who has no sword is humiliated.',
    'Live honorably or die honorably.',
    'Sometimes shoes are worse than going barefoot.',
    'Summer clouds are scattered by the morning wind; the journey is praised in the morning.',
    'I have water in my mouth, can someone with water in their mouth speak?',
    'Don’t complain to others; it’s like complaining to ravens and vultures.',
    'A duckling is a swimmer.',
    'Like father, like son.',
    'This cub is from that lion.',
    'The higher a noble person rises, the more humble they become; the higher a lowly person rises, the more arrogant they become.',
    'There is no nobility like humility and no honor like knowledge.',
    'If a true believer is found, all causes of success are found with him.',
    'The believer is patient when hungry and grateful when full.',
    'The believer is generous and noble, while the wicked is deceitful and lowly.',
    'I must create a system, or I will be enslaved by another man’s system.',
    'Where there is order, there is food; where there is chaos, there is hunger.',
    'The best way to destroy the capitalist system is to debase the value of money.',
    'Management works within the system, but leadership works above the system.',
    'Beautiful ornaments cover lean flesh.',
    'Freedom is not the absence of commitments, but the ability to choose what is best for me and bind myself to it.',
    'Life is not fair, so get used to it.',
    'In school, they teach you a lesson and then test you; in life, they test you and then teach you a lesson.',
    'Don’t be the head, the head suffers much harm.',
    'No prophet is honored in his own country.',
    'If you don’t drink the bitter with the clear, you will remain thirsty, and no one’s drink is entirely pure.',
    'If patience is bitter, its outcome is sweet.',
    'Be patient and you will achieve.',
    'Be patient for a while, after hardship comes ease; everything has a time and a plan.',
    'Be patient with every calamity and endure, knowing that time is not immortal.',
    'Times change. Patience is from God, haste is from Satan.',
    'Panic in the face of a calamity is itself a calamity.',
    'Conjunctivitis is better than blindness.',
    'Patience is of two kinds: patience with what you dislike and patience with what you like.',
    'Patience at the first shock.',
    'Patience is the key to relief.',
    'The sky is hoped for when it is overcast.',
    'God delays but does not neglect.',
    'Tomorrow is near to those who watch for it.',
    'Today has tomorrow within it, oh happy one.',
    'I am already drowning, why fear getting wet?',
    'With patience, opportunities are grasped.',
    'Every living thing has a lifespan.',
    'Every disease has a cure.',
    'If you mention the wolf, take precautions.',
    'The end of life is death.',
    'If the face loses its water, it loses its modesty; a face without water is worthless.',
    'When fate comes, space narrows.',
    'If you escape the lion, don’t covet its prey.',
    'If you wrong those below you, don’t expect safety from those above you.',
    'If your hand cannot reach to repay, let your tongue repay with thanks.',
    'If speech is silver, silence is gold.',
    'Some tolerance is humiliation.',
    'One hand cannot carry two watermelons.',
    'Take wisdom from the mouths of the simple.',
    'Not everything known is said.',
    'Sit where your hand is taken and honored, not where your foot is taken and dragged.',
    'Treat people well and you will enslave their hearts. If the mind is complete, speech decreases.',
    'Every stranger is a relative to another stranger.',
    'Sacrifice your blood and wealth for your friend.',
    'Cheating a friend is vile.',
    'Beware of your enemy once and your friend a thousand times, for a friend turned enemy knows more harm.',
    'Make allies of peers and be kind to enemies.',
    'Your brother is the one who tells you the truth, not the one who agrees with you.',
    'The best brothers are the oldest.',
    'If friendship is maintained, its inside is better than its outside.',
    'If you find fault in all matters with your friend, you will not find one you do not fault.',
    'Know your companion and let him be.',
    'Leadership is sweet to suckle, bitter to wean.',
    'The neighbor is first in purchase rights.',
    'The neighbor before the house.',
    'A friend either helps or intercedes.',
    'A friend in need is a friend indeed.',
    'Reproach is a gift from lovers.',
    'The absent has his excuse with him.',
    'In good morals, there are treasures of provisions.',
    'Be sincere in your work to achieve your highest goals.',
    'The drowning man clutches at a straw.',
    'Spend what is in your pocket, and the unseen will come to you.',
    'A well-mannered child is a joy in adulthood.',
    'Punish the saddle to make the donkey think.',
    'Whoever exhausts me teaches me strength.',
    'Who grows up on something, grows old on it.',
    'Safety is in patience, regret is in haste.',
    'The hasty errs even if he is a king, the patient succeeds even if he perishes.',
    'Who hurries stumbles often.',
    'Who is patient achieves what he wishes.',
    'Mistakes are the food of the hasty.',
    'With patience, demands are easily met.',
    'Who rides haste meets blunders.',
    'No bird has flown and risen but as it has flown, it has fallen.',
    'Only the lowly are arrogant, the high are humble.',
    'God protect me from my friends; I can handle my enemies.',
    'People support each other.',
    'Solitude is better than a bad companion.',
    'Your brother is the one who supports you.',
    'When a scholar errs, an entire world errs with him.',
    'If you strike, strike hard; blame is the same.',
    'If you have an opinion, be resolute.',
    'When opinion triumphs, desire perishes.',
    'Send a wise man, do not advise him.',
    'Tighten, oh crisis, you will be released.',
    'The hardest struggle is against anger.',
    'The greatest poverty is lack of intellect.',
    'Happiness is good health and a bad memory.',
    'Seek a bride for your daughter, not a groom for your son.',
    'Someone a day older knows better by a year.',
    'A mother is a school; if you prepare her, you prepare a noble people.',
    'The belly does not bear an enemy.',
    'Experiences are endless, and a person gains more from them.',
    'Experience is the great science.',
    'A slave is disciplined with the stick, a free man with a hint.',
    'Blame lies with the eyes.',
    'Knowledge is light.',
    'Knowledge and reason are two necessary allies.',
    'Reason and etiquette are companions.',
    'A heart devoid of reason is devoid of knowledge.',
    'Intelligence is better than inherited wealth.',
    'Arrogance without strength is debasement.',
    'Intellect is the best weapon.',
    'A clear mind is the best fortress.',
    'The intelligent is the one who profits from his experience, and the fool is the one who doesn’t.',
    'A thought before action is safety.',
    'Knowledge and action are brothers.',
    'Don’t trust someone who is disloyal to their faith, how can they be loyal to you?',
    'A matter persists as long as it has a reason.',
    'There is no gratitude in generosity when one is able.',
    'Who is used to getting up early will not sleep.',
    'An idle person is not a benefactor.',
    'A scholar’s mistake is like a shipwreck; many drown because of it.',
    'Whoever is guided by reason will see the right path.',
    'Good intentions don’t change facts.',
    'Good manners are the virtue of nobles.',
    'Good behavior is a source of comfort.',
    'Who learns young reaps benefits when old.',
    'Life with hope is better than life with despair.',
    'A sincere person is beloved to God.',
    'One who is honest will not be regretted.',
    'Honesty guides to righteousness.',
    'Who sows good reaps it.',
    'Be honest even if it harms you, for truth is a remedy for many ailments.',
    'The truthful is trusted.',
    'Honesty brings honor.',
    'Cleverness is in telling the truth.',
    'Honesty is an adornment.',
    'Truthfulness is a virtue of the prophets.',
    'A truthful person is strong.',
    'A truthful person is respected.',
    'A truthfulness in words and deeds.',
    'Honesty in deeds.',
    'True faith in deeds, not words.',
    'Who cheats in word and deed is despised.',
    'The honest is beloved.',
    'The trustworthy is beloved to God.',
];

export default (className) =>
    Widget.Label({
        className: className || 'saying-wd-label',
        // label: "SUIII",
        justification: local === 'RTL' ? 'left' : 'right',
        // truncate: 'end',
        xalign: 0,
        maxWidthChars: 24,
        wrap: true,
    }).poll(30 * 1000 * 60, (self) => {
        const selectedWordsDict = local === 'RTL' ? wordsDictAr : wordsDictEn;
        // const selectedWordsDict = wordsDictEn;

        const randomIndex = Math.floor(
            Math.random() * selectedWordsDict.length
        );

        // Use the random index to get a random element
        const randomSaying = selectedWordsDict[randomIndex];

        self.label = randomSaying;
    });
