import { local } from '../utils/helpers.js';
import { Widget } from '../utils/imports.js';

const wordsDictAr = [
    'لِتبرَأ الرُّوح مِن ضِيقٍ ومِن كَدَرٍ - ويَبْرأ الجِسْمُ مِن وَهْنٍ ومِن سَغَبِ',
    'لَكَم نُغالِبُ في الأيّامِ مِن كَبَدٍ - نَظُنُّ أنّ هَنَاء العَيْشِ في الغَلَبِ',
    'إلى حتفي مَشَتْ قدمي.',
    'اليوم خمر وغداً أمر.',
    'تجري الرياح بما لا تشتهي السفن.',
    'حنانيك بعض الشر أهون من بعض.',
    'رُبَّ دهر بكيت منه فلما صرت في غيره بكيت عليه.',
    'رُبَّ ملوم لا ذنب له.',
    'قُتل رحمه الله” خير من “فر أخزاه الله”.',
    'أخاك أخاك إن مَنْ لا أخاً له كَساعٍ إلى الهيجا بغير سلاح.',
    'أخوك من صدقك النصيحة.',
    'إذا غامَرْتَ في شرف مروم فلا تقنع بما دون النجوم.',
    'إذا لم يكن إلا الأَسِنَّةُ مركباً فلا رأي للمضطر إلا ركوبها.',
    'السعادة والرضا أدوات تجميل عظيمة، وأدوات خادعة لحفظ مظهر الشباب.',
    'تزيين الجسم أسرع من تزيين النفس.',
    'ليست البقرة الأقوى خواراً، هي البقرة الأكثر مدراراً.',
    'من لا يعرف التصنع لا يعرف العيش.',
    'ما فائدة الدنيا الواسعة، إذا كان حذاؤك ضيقاً.',
    'الدعوة للحرية ليس معناها دعوة للإنفلات والفوضى والهمجية الحرية قيمة عظيمة ولكن القاعدة: أنت حر ما لم تضر.',
    'إذا كانت الحرية ضعيفة التسليح فعلينا تسليحها بقوة الارادة.',
    'استقبال الموت خير من استدباره.',
    'أكرم نفسك عن كل دنيء.',
    'الإفراط في التواضع يجلب المذلة.',
    'الجود بالنفس أقصى غاية الجود.',
    'السيف أهول ما يُرى مسلولاً.',
    'العز في نواصي الخيل.',
    'القَصَّابُ لا تهوله كثرة الغنم.',
    'إن البعوضة تُدْمي مُقْلةَ الأسد.',
    'إن الجبان حتْفُه من فوقه.',
    'إن القذى يؤذي العيون قليله ولربما جرح البعوض الفيلا.',
    'أنا لها ولكل عظيمة.',
    'بنفسي فَخَرْتُ لا بجدودي.',
    'تجوع الحرة ولا تأكل بثدييها.',
    'تعدو الذئاب على من لا كلاب له وتتقي صولة المستنفر الحامي.',
    'ذل من لا سيف له.',
    'عش عزيزاً أو مت وأنت كريم.',
    'رُبَّ نعل شر من الحفا.',
    'سحابة صيف تذروها الرياح عند الصباح يحمد القوم السرى.',
    'في فمي ماء وهل ينطق من في فمه ماء.',
    'لا تشكون إلى خلق فتشمته شكوى الجريح إلى الغربان والرخم.',
    'فرخ البط عوام.',
    'من شابه أباه فما ظلم.',
    'هذا الشبل من ذاك الأسد.',
    'كلما ارتفع الشريف تواضع، وكلما ارتفع الوضيع تكبر.',
    'لا حسب كالتواضع ولا شرف كالعلم.',
    'إذا وجد المؤمن الصحيح وجدت معه أسباب النجاح جميعاً.',
    'المؤمن إذا جاع صبر وإذا شبع شكر.',
    'المؤمن غر كريم والفاجر خب لئيم.',
    'يجب أن أخترع نظاماً وإلا فسيستعبدني نظام رجل أخر.',
    'حيث النظام نجد الطعام حيث الفوضى تجد الجوع.',
    'أفضل وسيلة لتدمير النظام الرأسمالي هو إفساد قيمة المال.',
    'الأدارة تعمل من خلال النظام أما القيادة فتعمل فوق النظام.',
    'الزينة الجميلة تغطي لحماً هزيلاً.',
    'ليست الحرية غياب الالتزامات انما هي القدرة على أختيار ما هو أفضل لي وإلزام نفسي به.',
    'الحياة ليست عادلة، فلتعود نفسك على ذلك.',
    'في المدرسة يعلمونك الدرس ثم يختبرونك، أما الحياة فتختبرك ثم تعلمك الدرس.',
    'لا تكن رأساً فالرأس كثير الأذى.',
    'لا كرامة لنبيّ في وطنه.',
    'إذا أنت لم تشرب مراراً على القذى ظمئت وأي الناس تصفو مشاربه.',
    'إذا كان الصبر مُرًّاً فعاقبته حلوة.',
    'اصبر تنل.',
    'اصبر قليلاً فبعد العسر تيسير وكل أمر له وقت وتدبير.',
    'اصبر لكل مُصِيبةٍ وتجلًّدِ واعلم بأن الدهر غير مُخَلَّدِ.',
    'الأيام دول. التأني من الرحمن والعجلة من الشيطان.',
    'الجزع عند المصيبة مصيبة.',
    'الرمد أهون من العمى.',
    'الصبر صبران: صبر على ما تكره وصبر على ما تحب.',
    'الصبر عند الصدمة الأولى.',
    'الصبر مفتاح الفرج.',
    'إن السماء تُرْجَى حين تحتجب.',
    'إن الله يمهل ولا يهمل.',
    'إن غداً لناظره قريب.',
    'إن مع اليوم غداً يا مسعدة.',
    'أنا الغريق فما خوفي من البلل. بالتأني تُدْرَكُ الفُرَصُ.',
    'لكل حي أجل.',
    'لكل داء دواء.',
    'إذا ذكرت الذئب فخذ الحذر.',
    'آخر الحياة الموت.',
    'إذا قل ماء الوجه قل حياؤه، ولا خير في وجه إذا قل ماؤه.',
    'إذا حان القضاء ضاق الفضاء.',
    'إذا سلمت من الأسد فلا تطمع في صيده.',
    'إذا ظلمت من دونك فلا تأمن عقاب من فوقك.',
    'إذا قصرت يدك عن المكافأة فليصل لسانك بالشكر.',
    'إذا كان الكلام من فضة فالسكوت من ذهب.',
    'بعض الحلم ذل.',
    'يد واحدة لا تحمل بطيختين.',
    'خذوا الحكمة من أفواه البسطاء.',
    'ما كلُّ ما يُعلم يُقال.',
    'اجلس حيث يُؤْخَذُ بيدك وَتُبَرُّ ولا تجلس حيث يؤخذ برجلك وتُجَرُّ.',
    'أَحْسِنْ إلى الناس تستعبد قلوبهم. إذا تم العقل نقص الكلام.',
    'كل غريب للغريب نسيب.',
    'ابذل لصديقك دمك ومالك.',
    'غبن الصديق نذالة.',
    'احذر عدوك مرة وصديقك ألف مرة فإن انقلب الصديق فهو أعلم بالمضرة.',
    'آخ الأْكْفاءَ وداه الأعداء.',
    'أخوك من صَدَقك لا من صدّقك.',
    'خير الإخوان أقدمهم.',
    'إذا صُنْتَ المودة كان باطنها أحسن من ظاهرها.',
    'إذا كنت في كل الأمور معاتباً صديقك لم تلق الذي لا تعاتبه.',
    'اعرف صاحبك واتركه.',
    'الإمارة حلوة الرضاع مُرَّةُ الفطام.',
    'الجار أولى بالشُّفْعَةِ.',
    'الجار قبل الدار.',
    'الصديق إما أن ينفع وإما أن يشفع.',
    'الصديق وقت الضيق.',
    'العتاب هدية الأحباب.',
    'الغائب عُذْرُه معه.',
    'في سعة الأخلاق كنوز الأرزاق.',
    'كن مخلصاً في عملك تبلغ أقصى أملك.',
    'الغريق يتمسك بقشة.',
    'أنفق ما في الجيب، يأتيك ما في الغيب.',
    'من أدب ولده صغيراً سر به كبيراً.',
    'أجلد السرج لكي تحمل الحمار على التفكير.',
    'من أنهكني علمني القوة.',
    'من شب على شيء شاب عليه.',
    'في التأني السلامة وفي العجلة الندامة.',
    'العجول مخطيء ولو ملك، والمتأني مصيب وإن هلك.',
    'من أسرع كثر عثاره.',
    'من تأنى نال ما تمنى.',
    'الخطأ زاد العجول.',
    'بالتأني تسهل المطالب.',
    'من ركب العجلة أدركه الزلل.',
    'ما طار طير وارتفع إلا كما طار وقع.',
    'لا يتكبر إلا كل وضيع، ولا يتواضع إلا كل رفيع.',
    'اللهم قني شر أصدقائي أما أعدائي فأنا كفيل بهم.',
    'الناس لبعضها.',
    'الوَحْدَةُ خير من جليس السوء.',
    'إن أخاك من واساك.',
    'إذا زل العالِمُ زل بزلته عالَمٌ.',
    'إذا ضربت فأوجع فإن الملامة واحدة.',
    'إذا كنت ذا رأي فكن ذا عزيمة.',
    'إذا نُصِرَ الرأي بطل الهوى.',
    'أرسل حكيماً ولا توصه.',
    'اشتدي يا أزمة تنفرجي.',
    'أشد الجهاد مجاهدة الغيظ.',
    'أشد الفاقة عدم العقل.',
    'السعادة صحة جيدة وذاكرة سيئة.',
    'اخطب لبنتك ولا تخطب لابنك.',
    'أكبر منك بيوم يعرف عنك بسنة.',
    'الأم مدرسة إذا أعددتها أعددت شعباً طيب الأعراق.',
    'البطن لا تلد عدواً.',
    'التجارب ليست لها نهاية والمرء منها في زيادة.',
    'التجربة العلم الكبير.',
    'العبد يقرع بالعصا والحر تكفيه الإشارة.',
    'العتب على النظر.',
    'العلم زين فكن للعلم مكتسباً وكن له طالبًا ما عشت مقتبسا.',
    'العلم يجدي ويبقى للفتى أبدا والمال يفنى وإن أجدى إلى حين.',
    'العلم يرفع بيتاً لا عماد له والجهل يهدم بيت العز والشرف.',
    'القرد في عين أمه غزال.',
    'الكتاب يقرأ من عنوانه.',
    'إذا دببت على المنسأة من هرم فقد تباعد عنك اللهو والغزل.',
    'إذا عُرِفَ السبب بطل العجب.',
    'وإذا كانت النفوس كباراً تعبت في مرادها الأجسام.',
    'اطلب من العلوم علماً ينفعك ينفي الأذى والعيب ثم يرفعك.',
    'أعدل الشهود التجارب.',
    'أعز من الولد ولد الولد.',
    'أعز مكان في الدنا سرج سابح وخير جليس في الزمان كتاب.',
    'خادم سيدين يكذب على أحدهما.',
    'إذا سمعت الرجل يقول فيك من الخير ما ليس فيك فلا تأمن أن يقول فيك من الشر ما ليس فيك.',
    'أذل البخل أعناق الرجال.',
    'أرى كل إنسان يرى عيب غيره ويعمى عن العيب الذي هو فيه.',
    'أساء سمعاً فأساء إجابة.',
    'أسد عليَّ وفي الحروب نعامة.',
    'أعلمه الرماية كل يوم فلما أشتد ساعِدُهُ رماني.',
    'أغنى الأغنياء من لم يكن للبخل أسيراً.',
    'آفة الحديث الكذب. أقل الناس سروراً الحسود.',
    'أكلوا خيري وعصوا أمري.',
    'البخيل عظيم الرواق صغير الأخلاق.',
    'البخيل غناه فقر ومطبخه قفر.',
    'البخيل لا تَبُلُّ إحدى يديه الأخرى.',
    'اجتنب مصاحبة الكذاب فإن اضطررت إليه فلا تُصَدِّقْهُ.',
    'أجهل الناس من كان على السلطان مدلاً وللإخوان مذلاً.',
    'أحضر الناس جواباً من لم يغضب.',
    'اختلط حابلهم بنابلهم.',
    'إذا تفرقت الغنم قادتها العنز الجرباء.',
    'إذا ساء فعل المرء ساءت ظنونه وَصَدَّقَ ما يعتاده من توهم.',
    'إذا سأل ألحف وإن سئل سوّف.',
    'احفر بئراً وَطُمَّ بئراً ولا تُعَطِّلْ أجيرا.',
    'احفظ قرشك الأبيض ليومك الأسود.',
    'إذا كنت سنداناً فاصبر وإذا كنت مطرقة فأوجع.',
    'إذا هَبَّتْ رياحك فاغتنمها.',
    'استر عورة أخيك لما يعلمه فيك.',
    'اشكر من أَنْعَمَ عليك وأَنْعِمْ على من شكرك.',
    'اِضْرِبْ ما دام الحديد حامياً.',
    'اعقلها وتوكل.',
    'اعمل الطيب وارمه البحر.',
    'أفضل الجود أن تبذل من غير مسألة.',
    'أقلل عتابك فالبقاء قليل والدهر يعدل تارة ويميل.',
    'وانهض فوراً مستبشراً ، فتلك هي أولى درجات النجاح.',
    'عندما يرن الهاتف ابتسم وأنت تتلقى السماعة، فإن محدثك على الطرف الآخر سيرى ابتسامتك من خلال نبرات صوتك.',
    'تزوج من تجيد المحادثة، فعندما يتقدم بك العمر ستعرف أهمية ذلك، عندما يصبح الحديث مع من تحب قمة أولوياتك واهتماماتك.',
    'إذا أحببت شخصاً فاذهب إليه وقل إنك تحبه ، إلّا إذا كنت لا تعني ما تقول فعلاً ! لأنه سيعرف الحقيقة بمجرد النظر في عينيك.',
    'لا تتردد في أن تتأسف لمن أخطأت في حقه ، وانظر لعينيه وأنت تنطق بكلمات الاعتذار ، ليقرأها في عينيك وهو يسمعها بأذنيه.',
    'لا تحكم على شخص من أقربائه فقط ، فالإنسان لم يختر والديه ، فما بالك بأقربائه.',
    'عندما لا تريد الإجابة على سؤال ، فابتسم للسائل قائلاً: هل تعتقد أنه فعلاً من المهم.',
    'لا تدع الأشياء الصغيرة تدمر صداقتك الغالية مع الآخرين ، فالصداقة الحقيقية تاج على رؤوس البشر ، لا يدركه إلا سكان الجدران الخالية والقلوب الخاوية.',
    'لا تسخر من الآخرين وأحلامهم الوردية الجميلة ، خاصة من تعتقد أنهم أقل منك من البسطاء الطيبين ، فلربما تكون منزلة خادمك عند الله أسمى وأرفع منك ومن كثير من علياء القوم ، وقد تحظى بشفاعتهم يوم القيامة، ولا تقلل من شأن الأحلام ، فالدنيا بدونها رحلة جافة ومملة مهما يكن الواقع جميلا.',
    'فكر كثيراً ، واستنتج طويلا ، وتحدث قليلاً، ولا تهمل كل ما تسمعه ! فمن المؤكد أنك ستحتاجه في المستقبل.',
    'من يغرق يتعلق بعود قش.',
    'أعزب دهر ولا أرمل شهر.',
    'اعطني عمر وارميني بالبحر.',
    'ألا كل ما هو آت قريب وللأرض من كل حي نصيب.',
    'الحصاة من الجبل.',
    'الصباح رباح.',
    'العمر واحد والرب واحد.',
    'المأمول خير من المأكول.',
    'أول الشجرة بذرة.',
    'البعيد عن العين بعيد عن القلب.',
    'الحب أعمى.',
    'من أحب ولده رحم الأيتام.',
    'القلوب عند بعضها.',
    'إن العيون التي في طرفها حور قتلننا ثم لم يحيين قتلانا يَصرَعْنَ ذا اللب حتى لا حراك به وهن أضعف خلق الله إنسانا.',
    'أول الشجرة بذرة.',
    'ربك رب قلوب.',
    'فإن قليل الحب بالعقل صالح وإن كثير الحب بالجهل فاسد.',
    'لا تخف ما صنعت بك الأشواق .. واشرح هواك فكلنا عشاق.',
    'مرآة الحب عمياء.',
    'من القلب للقلب رسول.',
    'رب بعيد أنفع من قريب.',
    'فيا ليت الشباب يعود يوماً فأخبره بما فعل المشيب.',
    'كلكم طلب صيد.',
    'ما أبعد ما فات وما أقرب ما يأتي.',
    'ما كل ما يتمنى المرء يدركه تجرى الرياح بما لا تشتهي السفن.',
    'كل حبل على غاربه.',
    'ما أشبه الليلة بالبارحة.',
    'أثقل من جبل.',
    'أحذر من غراب.',
    'أحرس من كلب.',
    'أدنى من حبل الوريد.',
    'أرخص من التمر في البصرة.',
    'أسرع من الريح.',
    'أقرب من اللسان للأسنان.',
    'البعد جفاء.',
    'البياض نصف الحسن.',
    'الماء أهون موجود وأعز مفقود.',
    'المتكبر كالواقف على الجبل يرى الناس صغاراً ويرونه صغيراً.',
    'أتبع من الظل.',
    'إنه أشبه به من التمرة بالتمرة.',
    'سارت به الرُّكْبانُ.',
    'عاد الأمر إلى نصابه.',
    'فالوجه مثل الصبح مبيض والشعر مثل الليل مسود.',
    'فما تحمد العينان كل بشاشة ولا كل وجه عابس بذميم.',
    'لسان المرء من خدم الفؤاد.',
    'صاحب الحق عينه قوية.',
    'على الباغي تدور الدوائر.',
    'كما تدين تدان.',
    'لا يَفُلُّ الحديد إلا الحديد.',
    'من عَفَّ عن ظلم العباد تورعاً جاءته ألطاف الإله تبرعا.',
    'هذه بتلك والبادئ أظلم.',
    'هي النفس ما حَمَّلْتَها تتحمل وللدهر أيام تجور وتَعْدِلُ.',
    'ما أشبه الليلة بالبارحة.',
    'من يخشى البلل لا يصطاد السمك.',
    'معظم النار من مستصغر الشرر.',
    'اترك الشر يتركك.',
    'احذر الأحمق واحذر وُدَّهُ إنما الأحمق كالثوب الْخَلَق.',
    'احذروا من لا يرجى خيره ولا يؤمن شره.',
    'إذا جاء الحين حارت العين.',
    'إذا ذكرت الذئب فأعد له العصا.',
    'إذا رأيت نيوب الليث بارزة فلا تظنن أن الليث يبتسم.',
    'إذا كنتَ ذا رأىٍ فكن ذا مشورة فإن فساد الرأي أن تترددا.',
    'أعدّوا لكلب السوء كلباً يعادله.',
    'أقلل طعامك تجد منامك.',
    'الدهر يومان حلو ومر.',
    'اللي يخاف من العفريت يطلع له.',
    'إن الجواد قد يعثر.',
    'إن الشفيق بسوء ظن مولع.',
    'إن كنت ريحاً فقد لاقيت إعصارا.',
    'إن وراء الأَكَمةِ ما وراءها.',
    'خُذْهُ بالموت حتى يرضى بالحُمَّى.',
    'راحت السكرة وجاءت الفكرة.',
    'ستبدي لك الأيام ما كنت جاهلاً.',
    'قد يخرج من الصدفة غير الدُّرَّة.',
    'أَدّى قدراً مستعيرها.',
    'إذا أتاك أحد الخصمين وقد فُقِئَتْ عينه فلا تقض له حتى يأتيك خصمه فلعله قد فُقِئَتْ عيناه.',
    'إذا تولى عقداً أحكامه.',
    'الجزاء من جنس العمل.',
    'الحق دولة والباطل جولة.',
    'الرجوع إلى الحق خير من التمادي في الباطل.',
    'العاقل لا يبطل حقاً ولا يحق باطلاً.',
    'العدل أساس الْمُلْك.',
    'العين بالعين والسن بالسن.',
    'إذا أردت أن تطاع فأمر بما يستطاع.',
    'إذا المرء لم يدنس من اللؤم عرضه فكل رداء يرتديه جميل.',
    'إذا أنت أكرمت الكريم ملكته وإن أنت أكرمت اللئيم تمردا.',
    'كفى المرء فضلاً أن تُعَدَّ معايبه.',
    'إذا حضر الماء بطل التيمم.',
    'اذالم تستحي فأفعل ما تشاء.',
    'أطهر الناس أعراقاً أحسنهم أخلاقاً.',
    'أعرف الناس بالله أرضاهم بما قسم الله له.',
    'اعف عما أغضبك لما أرضاك.',
    'أفضل الجود العطاء قبل الموعد.',
    'الْبِشْرَ دال على الكرم.',
    'التكبر على المتكبر تواضع.',
    'التواضع من مصائد الشرف.',
    'الجودة من الموجودة.',
    'الحر تكفيه الإشارة.',
    'الحِلْمُ سيد الأخلاق.',
    'الدال على الخير كفاعله.',
    'الرفق بالجاني عتاب.',
    'السر أمانة.',
    'الشريف إذا تَقَوَّى تواضع والوضيع إذا تَقَوَّى تكبر.',
    'الناس الذين غيروا العالم هم الناس الذين واصلوا البحث عندما بدا الأمر مستحيلاً بالنسبة للآخرين.',
];

const wordsDictEn = [
    'To comfort the soul from distress and sorrow - and the body recovers from fatigue and weariness',
    "We persevere in hardship over the days - thinking that life's happiness lies in perseverance",
    'To my death, my feet walk.',
    'Today is wine, tomorrow is fate.',
    'The winds blow as the ships do not wish.',
    'Some of your tenderness is easier than some of your evil.',
    'Many a time have I cried over it, and when I found myself in another I cried over it.',
    'Many a time blamed without guilt.',
    "'May God have mercy on the one killed' is better than 'May God disgrace the one who flees'.",
    'Your brother, your brother, if he has no brother, is like a traveler to the barren without a weapon.',
    'Your brother is the one who believes your advice.',
    'If you venture into the honor of the intended, do not be satisfied with less than the stars.',
    'If there is nothing but the ship to sail, then the desperate has no choice but to board it.',
    'Happiness and satisfaction are great beauty tools, and deceptive tools to maintain youthful appearance.',
    'Body decoration is faster than soul decoration.',
    'The strongest cow is not the strongest, it is the most abundant.',
    'Whoever does not know artifice does not know how to live.',
    'What is the use of the vast world, if your shoe is narrow?',
    'Advocating for freedom does not mean advocating for licentiousness, chaos, and barbarism. Freedom is a great value, but the rule is: you are free as long as you do no harm.',
    'If freedom is poorly armed, we must arm it with the power of will.',
    'Receiving death is better than summoning it.',
    'Honor yourself above all despicable things.',
    'Excess humility brings humiliation.',
    'Self-esteem is the ultimate generosity.',
    'The sword is most terrifying when seen drawn.',
    'Honor lies in the flanks of horses.',
    'The butcher is not frightened by the abundance of sheep.',
    'The mosquito can blind the eye of a lion.',
    "The coward's death is from above him.",
    'Vermin harms the eyes, even the little ones, and perhaps a mosquito wounds an elephant.',
    'I am for her and for every great one.',
    'I am proud of myself, not of my ancestors.',
    'The free woman starves and does not feed with her breasts.',
    'Wolves prey on those who have no dogs and fear the coming of the alert guard.',
    'Humiliation is for those who have no sword.',
    'Live proudly or die as a generous person.',
    'A sandal may be worse than a slipper.',
    'A summer cloud, dispersed by the wind at dawn, praises the secret deeds of the people.',
    'There is water in my mouth, and can someone with water in his mouth speak?',
    'Do not complain to people lest they make fun of you, the wounded complain to crows and vultures.',
    'The duckling is afloat.',
    'Whoever resembles his father has not done wrong.',
    'This lion cub is from that lion.',
    'The nobler one becomes, the more humble; the more base, the more arrogant.',
    'Neither humility nor honor is like knowledge.',
    'If the believer finds support, he finds with it all the means of success.',
    'When the believer is hungry, he is patient, and when he is full, he is grateful.',
    'The believer is a generous stranger, and the wicked one is a vile misanthrope.',
    "I must invent a system, otherwise, another man's system will enslave me.",
    'Where there is a system, we find food; where there is chaos, we find hunger.',
    'The best way to destroy the capitalist system is to undermine the value of money.',
    'Management works through the system, while leadership works above the system.',
    'Beautiful adornment covers frail flesh.',
    'Freedom is not the absence of commitments, but the ability to choose what is best for me and obligate myself to it.',
    'Life is not fair, so get used to it.',
    'In school, they teach you the lesson then test you, but life tests you first then teaches you the lesson.',
    "Don't be a know-it-all; a head full of knowledge can be dangerous.",
    'There is no dignity for a prophet in his homeland.',
    'If you have not drunk from the bitter cup, you have thirsted, and which people are those who purify their streams.',
    'If patience is bitter, then its outcome is sweet.',
    'Be patient, and you will achieve.',
    'Be patient a little, and you will feel the sweetness of faith.',
    'Patience is the key to relief.',
    'If you have patience, then even the smallest ant can cross a great river.',
    'If the patient person knows how to be patient, he becomes the most patient.',
    'Patience is the key to paradise.',
    'It is not enough to see patience as a virtue; you must practice it.',
    'Patience is the key to victory.',
    'If you have patience, you have everything.',
    'Even if you have a small amount of patience, it can save you from great difficulties.',
    'Patience is the source of strength.',
    'Patience is the best of all characteristics.',
    'Patience in hardship is like the light in the darkness.',
    'Patience is the cornerstone of religion.',
    'You cannot cross the sea merely by standing and staring at the water.',
    'The beginning of all knowledge is the fear of God.',
    'Do not lose hope in the mercy of God.',
    "The beauty of God's creation is the reflection of His mercy.",
    'If you wish to speak to God, pray; if you wish for Him to speak to you, read the Quran.',
    'God is closer to you than your jugular vein.',
    "God's mercy is vast.",
    'Do not forget to call upon God for help.',
    'When God takes something away from you, He gives something better in return.',
    "God's timing is always perfect.",
    'Allah does not burden a soul beyond that it can bear.',
    'God does not look at your appearance or wealth; He looks at your heart and actions.',
    'God hears even the very silent prayer of a sincere heart.',
    "Allah's plan is always more beautiful than our desires.",
    'The mercy of Allah is infinite.',
    'God loves those who are patient.',
    'Allah is the best of planners.',
    'God is the source of all peace.',
    'There is no deity except Allah.',
    'Remember Allah much, and Allah will remember you.',
    'The closer you go to Allah, the more you will be content.',
    'Keep your heart attached to Allah.',
    'The Quran is the light of the heart.',
    'God will help those who help themselves.',
    "Trust Allah's timing.",
    "God's love is unconditional.",
    "Turn to Allah and repent before it's too late.",
    'Be grateful for the blessings Allah has given you.',
    'Allah is with the patient.',
    'No one can harm you when Allah protects you.',
    'If you put your trust in Allah, He will be sufficient for you.',
    'Faith can move mountains.',
    'Thank Allah for every blessing, whether big or small.',
    'Prayer is the key to all doors.',
    'When you feel alone, remember that Allah is with you.',
    "Allah's mercy is greater than your sins.",
    'When you have nowhere to turn, turn to Allah.',
    "God's mercy outweighs His wrath.",
    "The best way to repay Allah's favors is to show gratitude.",
    "Allah's love for you is greater than your own mother's love.",
    'The best provision is Taqwa (God-consciousness).',
    "Allah's blessings are countless.",
    'Turn to Allah before you return to Him.',
    "Trust in Allah's plan, even when you don't understand it.",
    "Allah's mercy is available to all who seek it.",
    'Allah knows what is best for you.',
    "Allah's love is eternal.",
    'Seek forgiveness from Allah; He is the most forgiving.',
    'Allah is the most compassionate, the most merciful.',
    "Trust Allah's wisdom, even if you don't understand it.",
    "Allah's mercy is greater than His wrath.",
    'Allah is the best listener; He hears even the very silent prayer of a sincere heart.',
    'Allah is the light of the heavens and the earth.',
    "Allah's help is near.",
    'Remember Allah in times of ease, and He will remember you in times of difficulty.',
    'The love of Allah is the greatest love of all.',
    "Allah's mercy encompasses all things.",
    'Allah guides whom He wills.',
    'Put your trust in Allah, and He will suffice you.',
    "Allah's mercy is boundless.",
    'When you feel lost, turn to Allah.',
    'Allah is the source of all strength.',
    'Turn to Allah before you return to Him.',
    'Allah is the best of protectors.',
    'Allah is the most merciful of those who show mercy.',
    'Allah knows what is in every heart.',
    "Allah's blessings are beyond measure.",
    'The love of Allah is the greatest love of all.',
    "Allah's mercy is infinite.",
    "Allah's mercy encompasses all things.",
    "Allah's mercy is greater than His wrath.",
    "Allah's mercy is for all.",
    'The love of Allah is the greatest love of all.',
    'Allah is the most compassionate, the most merciful.',
    "Trust in Allah's plan; He knows what is best for you.",
];

export default (className) =>
    Widget.Label({
        className: className || 'saying-wd-label',
        // label: "SUIII",
        justification: local === 'RTL' ? 'left' : 'right',
        // truncate: 'end',
        xalign: 0,
        maxWidthChars: 24,
        wrap: true,
    }).poll(30 * 1000 * 60, (self) => {
        const selectedWordsDict = local === 'RTL' ? wordsDictAr : wordsDictEn;
        // const selectedWordsDict = wordsDictEn;

        const randomIndex = Math.floor(
            Math.random() * selectedWordsDict.length
        );

        // Use the random index to get a random element
        const randomSaying = selectedWordsDict[randomIndex];

        self.label = randomSaying;
    });
